name: Trivy Scan

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scan:
    name: Trivy Vulnerability Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t insecure-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan and save report
        run: |
          mkdir -p trivy-results
          trivy image --format json -o trivy-results/result.json insecure-app

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-results/result.json

      - name: Parse Trivy and update CSV
        run: |
          python parse_trivy.py