permissions:
  contents: write

name: Trivy with CSV export

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t insecure-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan
        run: |
          mkdir -p trivy-results
          trivy image --format json -o trivy-results/result.json insecure-app

      - name: Convert Trivy result to CSV
        run: |
          python3 parse_trivy.py

      - name: Copy history.csv to docs/data.csv
        run: |
          mkdir -p docs
          cp trivy-results/history.csv docs/data.csv

      - name: Commit and push data.csv to main
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/data.csv
          git commit -m "Update data.csv from Trivy scan" || echo "No changes"
          git push
