name: Trivy Security Scan & Dashboard Update

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *' # optional: щоденний запуск

permissions:
  contents: write

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t insecure-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan
        run: |
          mkdir -p trivy-results
          trivy image --format json -o trivy-results/result.json insecure-app

      - name: Restore previous scan history if exists
        run: |
          if [ -f docs/data.csv ]; then
            mkdir -p trivy-results
            cp docs/data.csv trivy-results/history.csv
          fi

      - name: Parse Trivy JSON to CSV
        run: python3 parse_trivy.py

      - name: Copy CSV to dashboard directory
        run: |
          mkdir -p docs
          cp trivy-results/history.csv docs/data.csv

      - name: Show CSV content
        run: cat docs/data.csv

      - name: Commit updated data.csv to GitHub
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull origin main
          git add docs/data.csv
          git commit -m "Update Trivy dashboard data [skip ci]" || echo "Nothing to commit"
          git push origin main