name: Trivy with CSV export

on:
  push:
    branches: [main]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t insecure-app .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Run Trivy scan
        run: |
          mkdir -p trivy-results
          trivy image --format json -o trivy-results/result.json insecure-app

      - name: Convert Trivy result to CSV
        run: |
          python3 parse_trivy.py
          cat trivy-results/history.csv

      - name: Check contents of results
        run: ls -R trivy-results

      - name: Copy history.csv to docs/data.csv
        run: |
          mkdir -p docs
          cp trivy-results/history.csv docs/data.csv
          cat docs/data.csv

      - name: Check contents of docs/
        run: ls -R docs